spring.application.name=delivery

spring.datasource.url=jdbc:mysql://localhost:3306/delivery_lanchonete
spring.datasource.username=root
spring.datasource.password=tulioreis

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080